#echo 'cjdma'
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_test_mask_wo_entropy --score scores_deeplab_test_mask_wo_entropy --input ../dataset/test/images/

#echo 'dbdnjf'
python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/01
python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/02
python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/03
python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/04
python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/05
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/18
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/19
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/20
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/21
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/22
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/23
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/24
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/25
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/26
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/27
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/28
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/29
#python3 main.py --n_classes 2 --checkpoint /home/waggle/sp_models/using_models/models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input /storage/sunspot/001e06107d7f/2020_06/30

#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/05
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/06
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/07
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/08
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/18
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/19
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/20
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/21
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/22
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/23
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/24
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/25
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/26
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/27
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/28
#python3 main.py --n_classes 2 --checkpoint ../models/best_68000d_deeplabv3_resnet101_waggle_cloud_os16.pth --model deeplabv3_resnet101 --output output_deeplab_june_mask_wo_entropy --score scores_deeplab_june_mask_wo_entropy --input ../dataset/june/29
